// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3LUEu5ahUD3fUDsx-hs__pTvBq3C3ZFg',
    appId: '1:82728144426:web:91447051f11d4b78b9fd53',
    messagingSenderId: '82728144426',
    projectId: 'mydiary-d0294',
    authDomain: 'mydiary-d0294.firebaseapp.com',
    storageBucket: 'mydiary-d0294.appspot.com',
    measurementId: 'G-LTMTK610JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbejWIsp7g0X122f7qJwW3nPLKmv9PzT8',
    appId: '1:82728144426:android:994abef8f526a6f3b9fd53',
    messagingSenderId: '82728144426',
    projectId: 'mydiary-d0294',
    storageBucket: 'mydiary-d0294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrhfEHFRmLu3Z1w0RC-RUhT_xLkprqoDU',
    appId: '1:82728144426:ios:ec404e2f8da45c3cb9fd53',
    messagingSenderId: '82728144426',
    projectId: 'mydiary-d0294',
    storageBucket: 'mydiary-d0294.appspot.com',
    iosClientId: '82728144426-u0ehbct0ehbcujpp4rcbiv4s6ci88s83.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrhfEHFRmLu3Z1w0RC-RUhT_xLkprqoDU',
    appId: '1:82728144426:ios:389bf6fd133f537cb9fd53',
    messagingSenderId: '82728144426',
    projectId: 'mydiary-d0294',
    storageBucket: 'mydiary-d0294.appspot.com',
    iosClientId: '82728144426-ubbqv08ilqvrov07omj07qdkun9ktkl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDiary.RunnerTests',
  );
}
